name: Automation Tests

on:
  push:
    branches:
      - main  # Ana dalda yapılan her push işlemi tetikleyecek
  pull_request:
    branches:
      - main  # Ana dala yapılan her pull request işlemi tetikleyecek

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/  # Test raporlarının bulunduğu dizini belirtin
